# Generated by Django 4.1.2 on 2022-12-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileType',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Adult', 'Adult')], default=True, max_length=200),
            preserve_default=False,
        ),
    ]
