# Generated by Django 4.1.2 on 2022-11-13 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('movie_image', models.ImageField(upload_to='images')),
                ('movie_link', models.CharField(max_length=200)),
                ('movie_description', models.TextField()),
                ('movie_rating', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
