# Generated by Django 4.1.2 on 2022-12-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_year_of_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='movies',
            field=models.ManyToManyField(to='movies.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rated',
            field=models.CharField(choices=[('18', '18'), ('R', 'R'), ('PG-13', 'PG-13'), ('PG', 'PG'), ('G', 'G')], default=True, max_length=200),
            preserve_default=False,
        ),
    ]
