# Generated by Django 4.1.2 on 2022-12-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_categories_movies_movie_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_category', to='movies.categories'),
        ),
    ]
