# Generated by Django 4.1.2 on 2022-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='movies.movie'),
        ),
    ]
